### GET request for all deliveries
GET http://localhost:8082/api/deliveries

### GET request for courier 1
GET http://localhost:8082/api/couriers/550e8400-e29b-41d4-a716-446655440001

### GET request for courier 2
GET http://localhost:8082/api/couriers/550e8400-e29b-41d4-a716-446655440002

### GET request for courier 1 past orders
GET http://localhost:8082/api/couriers/550e8400-e29b-41d4-a716-446655440001/completed

### GET request for courier 2 past orders
GET http://localhost:8082/api/couriers/550e8400-e29b-41d4-a716-446655440002/completed

### POST request to claim order as courier (Uses your session id hardcoded in delivery controller)
POST http://localhost:8082/api/deliveries/770e8400-e29b-41d4-a716-446655440005/claim

### POST request to claim order as courier (Use it to try and claim an order when you already have one)
POST http://localhost:8082/api/deliveries/770e8400-e29b-41d4-a716-446655440006/claim

### POST request to claim an already claimed order
POST http://localhost:8082/api/deliveries/770e8400-e29b-41d4-a716-446655440001/claim