@courier1=550e8400-e29b-41d4-a716-446655440001
@courier2=550e8400-e29b-41d4-a716-446655440002
@delivery1=770e8400-e29b-41d4-a716-446655440001
@delivery2=770e8400-e29b-41d4-a716-446655440002
@delivery3=770e8400-e29b-41d4-a716-446655440003
@delivery4=770e8400-e29b-41d4-a716-446655440004
@delivery5=770e8400-e29b-41d4-a716-446655440005
@delivery6=770e8400-e29b-41d4-a716-446655440006


### GET request for all deliveries
GET http://localhost:8082/api/deliveries

### GET request for all unclaimed deliveries
GET http://localhost:8082/api/deliveries/unclaimed

### GET request for courier 1
GET http://localhost:8082/api/couriers/{{courier1}}

### GET request for courier 2
GET http://localhost:8082/api/couriers/{{courier2}}

### GET request for courier 1 past deliveries
GET http://localhost:8082/api/couriers/{{courier1}}/completed

### GET request for courier 2 past deliveries
GET http://localhost:8082/api/couriers/{{courier2}}/completed

### POST request to claim delivery as courier
POST http://localhost:8082/api/couriers/{{courier1}}/claim/{{delivery5}}

### POST request to claim delivery as courier (Use it to try and claim a delivery when you already have one)
POST http://localhost:8082/api/couriers/{{courier1}}/claim/{{delivery6}}

### POST request to claim an already claimed delivery
POST http://localhost:8082/api/couriers/{{courier1}}/claim/{{delivery1}}

### POST request to unclaim your claimed delivery
POST http://localhost:8082/api/couriers/{{courier1}}/unclaim

### POST request set delivery ready for pickup (Should only be preformed via order by restaurant)
POST http://localhost:8082/api/deliveries/{{delivery5}}/ready

