spring.application.name=delivery-service
server.port=8082

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=delivery
spring.datasource.username=user
spring.datasource.password=password

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:sql/data.sql

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

spring.rabbitmq.kdg.exchange-name=kdg_exchange
spring.rabbitmq.kdg.order-accepted-delivery-queue=order_accepted_delivery_queue
spring.rabbitmq.kdg.order-accepted-delivery-binding=order.accepted.delivery_service
spring.rabbitmq.kdg.order-ready-delivery-queue=order_ready_delivery_queue
spring.rabbitmq.kdg.order-ready-delivery-binding=order.ready.delivery_service
spring.rabbitmq.kdg.order-picked-up-binding=order.pickedUp
spring.rabbitmq.kdg.order-delivered-binding=order.delivered

domain.base-payout=3.0
domain.per-minute-payout=0.3
domain.minimum-minutes=5.0
domain.maximum-minutes=30.0

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/keepdishesgoing
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/certs